Repository tancheng/VectorCGRA, pull requests merged in 2025-04, with the labels that each got.

#108 [P0] Failing to write const/ctrl to CGRAs other than CGRA0 #106
  cgra/test/CgraRTL_test.py
  cgra/test/CgraTemplateRTL_test.py
  controller/ControllerRTL.py
  controller/test/ControllerRTL_test.py
  lib/messages.py
  mem/ctrl/test/CtrlMemDynamicRTL_test.py
  mem/ctrl/test/RingCtrlMemDynamicRTL_test.py
  mem/data/DataMemWithCrossbarRTL.py
  mem/data/test/DataMemWithCrossbarRTL_test.py
  scale_out/test/MeshMultiCgraRTL_test.py
  scale_out/test/RingMultiCgraRTL_test.py
  tile/test/TileRTL_test.py
Labels: bug

#111 Latch fixes
  cgra/test/CgraRTL_test.py
  cgra/test/CgraTemplateRTL_test.py
  controller/ControllerRTL.py
  mem/ctrl/CtrlMemDynamicRTL.py
  mem/ctrl/test/CtrlMemDynamicRTL_test.py
  mem/ctrl/test/RingCtrlMemDynamicRTL_test.py
  mem/data/DataMemWithCrossbarRTL.py
  noc/CrossbarRTL.py
  scale_out/test/MeshMultiCgraRTL_test.py
  scale_out/test/RingMultiCgraRTL_test.py
  systolic/test/Cgra3x3MemRightAndBottomRTL_matmul_2x2_test.py
  tile/TileRTL.py
  tile/test/TileRTL_test.py
Labels: cleanup

#113 [feature] Provide multi-cgra test
  .github/workflows/python-package.yml
  cgra/CgraRTL.py
  cgra/CgraTemplateRTL.py
  cgra/test/CgraRTL_test.py
  cgra/test/CgraTemplateRTL_test.py
  controller/ControllerRTL.py
  controller/test/ControllerRTL_test.py
  lib/messages.py
  mem/ctrl/CtrlMemDynamicRTL.py
  mem/ctrl/RingMultiCtrlMemDynamicRTL.py
  mem/ctrl/test/CtrlMemDynamicRTL_test.py
  mem/ctrl/test/RingCtrlMemDynamicRTL_test.py
  mem/data/DataMemWithCrossbarRTL.py
  mem/data/test/DataMemWithCrossbarRTL_test.py
  scale_out/MeshMultiCgraRTL.py
  scale_out/RingMultiCgraRTL.py
  scale_out/test/MeshMultiCgraRTL_test.py
  scale_out/test/RingMultiCgraRTL_test.py
  systolic/CgraSystolicArrayRTL.py
  systolic/test/Cgra3x3MemRightAndBottomRTL_matmul_2x2_test.py
  tile/TileRTL.py
  tile/test/TileRTL_test.py
Labels: bug

#118 Model CGRA with bottom and left mem
  .github/workflows/python-package.yml
  cgra/CgraRTL.py
  cgra/CgraTemplateRTL.py
  cgra/test/CgraRTL_test.py
  cgra/test/CgraTemplateRTL_test.py
  controller/ControllerRTL.py
  controller/test/ControllerRTL_test.py
  scale_out/MeshMultiCgraRTL.py
  scale_out/RingMultiCgraRTL.py
  scale_out/test/MeshMultiCgraRTL_test.py
  systolic/CgraSystolicArrayRTL.py
Labels: new feature

#119 [feature] Provide new type for cpu->noc xbar
  .github/workflows/python-package.yml
  cgra/test/CgraRTL_test.py
  cgra/test/CgraTemplateRTL_test.py
  controller/ControllerRTL.py
  controller/test/ControllerRTL_test.py
  fu/double/test/TwoPrlComboRTL_test.py
  fu/double/test/TwoSeqComboRTL_test.py
  fu/flexible/test/FlexibleFuRTL_hypothesis_test.py
  fu/flexible/test/FlexibleFuRTL_test.py
  fu/float/test/FpAddRTL_test.py
  fu/float/test/FpMulRTL_test.py
  fu/single/test/AdderCL_test.py
  fu/single/test/AdderRTL_test.py
  fu/single/test/AluRTL_test.py
  fu/single/test/BranchRTL_test.py
  fu/single/test/CompRTL_test.py
  fu/single/test/MemUnitRTL_test.py
  fu/single/test/MulRTL_test.py
  fu/single/test/PhiRTL_test.py
  fu/single/test/RetRTL_test.py
  fu/single/test/SelRTL_test.py
  fu/single/translate/CompRTL_test.py
  fu/triple/test/ThreeMulAluShifterRTL_test.py
  fu/vector/test/VectorAdderComboRTL_test.py
  fu/vector/test/VectorAdderRTL_test.py
  fu/vector/test/VectorAllReduceRTL_test.py
  fu/vector/test/VectorMulComboRTL_test.py
  fu/vector/test/VectorMulRTL_test.py
  fu/vector/translate/VectorAdderComboRTL_test.py
  fu/vector/translate/VectorMulComboRTL_test.py
  lib/messages.py
  lib/util/common.py
  mem/ctrl/test/CtrlMemDynamicRTL_test.py
  mem/ctrl/test/RingCtrlMemDynamicRTL_test.py
  mem/data/DataMemWithCrossbarRTL.py
  mem/data/test/DataMemWithCrossbarRTL_test.py
  mem/register_cluster/test/RegisterBankRTL_test.py
  mem/register_cluster/test/RegisterClusterRTL_test.py
  multi_cgra/MeshMultiCgraRTL.py
  multi_cgra/RingMultiCgraRTL.py
  multi_cgra/__init__.py
  multi_cgra/test/MeshMultiCgraRTL_test.py
  multi_cgra/test/RingMultiCgraRTL_test.py
  multi_cgra/test/RingNetworkRTL_test.py
  multi_cgra/test/__init__.py
  noc/test/CrossbarRTL_test.py
  systolic/test/Cgra3x3MemRightAndBottomRTL_matmul_2x2_test.py
  tile/test/TileRTL_test.py
Labels: bug, cleanup

#121 Update MeshMultiCgraRTL_test.py
  .github/workflows/python-package.yml
  fu/basic/TwoPrlCombo.py
  fu/double/test/TwoPrlComboRTL_test.py
  fu/float/FpAddRTL.py
  fu/float/FpMulRTL.py
  fu/float/test/FpAddRTL_test.py
  fu/float/test/FpMulRTL_test.py
  mem/data/DataMemWithCrossbarRTL.py
  multi_cgra/test/MeshMultiCgraRTL_test.py
Labels: bug

#129 Ubuntu 20.04 retirement.
  .github/workflows/python-package.yml
Labels: test

#131 Allow routing and compute to complete separately but be aware of each other
  mem/ctrl/CtrlMemDynamicRTL.py
  noc/CrossbarRTL.py
  tile/TileRTL.py
Labels: bug

#132 Separate routing rdy from FU
  fu/double/PrlMulAdderRTL.py
  fu/double/SeqMulAdderRTL.py
  fu/double/SeqMulShifterRTL.py
  multi_cgra/test/MeshMultiCgraRTL_test.py
  noc/CrossbarRTL.py
Labels: bug

#115 Add test_multi_CGRA_systolic_2x2_2x2
  cgra/CgraRTL.py
  doc/figures/multi_cgra_weight_stationary_systolic_array.png
  lib/messages.py
  mem/const/ConstQueueDynamicRTL.py
  mem/const/test/ConstQueueDynamicRTL_test.py
  multi_cgra/MeshMultiCgraRTL.py
  multi_cgra/test/MeshMultiCgraRTL_test.py
  tile/TileRTL.py
Labels: bug, test

#135 Update TileRTL.py
  tile/TileRTL.py
Labels: bug

#134 [P0] Deprecate systolic array #133
  .github/workflows/python-package.yml
  cgra/test/CgraRTL_test.py
  doc/figures/multi_cgra_weight_stationary_systolic_array.png
  doc/figures/weight_stationary_systolic_array.png
  multi_cgra/test/MeshMultiCgraRTL_test.py
  systolic/CgraSystolicArrayRTL.py
  systolic/__init__.py
  systolic/test/Cgra3x3MemRightAndBottomRTL_matmul_2x2_test.py
  systolic/test/__init__.py
Labels: test

#136 Add test_tapeout_2x2_2x2
  multi_cgra/test/MeshMultiCgraRTL_test.py
Labels: test

#139 Update MulRTL.py
  fu/single/MulRTL.py
Labels: cleanup
