Repository tancheng/VectorCGRA, pull requests merged in 2025-07, with the labels that each got.

#142 [feat] Add multi-cycle FUs
  cgra/test/CgraRTL_test.py
  fu/flexible/FlexibleFuRTL.py
  fu/single/DivRTL.py
  fu/single/ExclusiveDivRTL.py
  fu/single/InclusiveDivRTL.py
  fu/single/division.v
  fu/single/test/DivRTL_test.py
  fu/single/test/ExclusiveDivRTL_test.py
  fu/single/test/InclusiveDivRTL_test.py
  fu/single/translate/ExclusiveDivRTL_test.py
  fu/single/translate/InclusiveDivRTL_test.py
  lib/opt_type.py
  tile/test/TileRTL_test.py
Labels: bug, new feature

#160 Prototype FIR test
  cgra/test/CgraFL_test.py
  cgra/test/CgraRTL_fir_demo_test.py.disabled
  cgra/test/CgraRTL_fir_test.py
  cgra/test/CgraRTL_test.py
  cgra/test/config_fir.json
  cgra/test/dfg_fir.json
  cgra/test/fir.png
  cgra/test/mapping.out
  fu/single/PhiRTL.py
  fu/single/test/PhiRTL_test.py
  noc/CrossbarRTL.py
  tile/TileRTL.py
Labels: test

#161 Grant predicate
  cgra/test/CgraRTL_fir_test.py
  cgra/test/CgraRTL_test.py
  cgra/test/CgraTemplateRTL_test.py
  fu/flexible/test/FlexibleFuRTL_hypothesis_test.py
  fu/flexible/test/FlexibleFuRTL_test.py
  fu/single/BranchRTL.py
  fu/single/GrantRTL.py
  fu/single/test/BranchRTL_test.py
  fu/single/test/GrantRTL_test.py
  lib/opt_type.py
  lib/util/map_helper.py
  multi_cgra/test/MeshMultiCgraRTL_test.py
  tile/TileRTL.py
  tile/test/TileRTL_test.py
Labels: new feature
