Repository tancheng/VectorCGRA, pull requests merged in 2025-02, with the labels that each got.

#76 [fix] Fix combinational loops in VectorAdder and VectorMul
  fu/vector/VectorAdderRTL.py
  fu/vector/VectorMulRTL.py
Labels: bug

#78 [feature] Move buffer at xbar inport from outport
  cgra/CgraRTL.py
  cgra/CgraTemplateRTL.py
  cgra/test/CgraRTL_test.py
  cgra/test/CgraTemplateRTL_test.py
  lib/messages.py
  lib/util/common.py
  mem/ctrl/CtrlMemDynamicRTL.py
  mem/ctrl/test/CtrlMemDynamicRTL_test.py
  mem/ctrl/test/RingCtrlMemDynamicRTL_test.py
  mem/register_cluster/RegisterBankRTL.py
  mem/register_cluster/RegisterClusterRTL.py
  mem/register_cluster/__init__.py
  mem/register_cluster/test/RegisterBankRTL_test.py
  mem/register_cluster/test/RegisterClusterRTL_test.py
  mem/register_cluster/test/__init__.py
  noc/CrossbarRTL.py
  noc/OrLinkRTL.py
  noc/SelectorRTL.py
  noc/test/OrLinkRTL_test.py
  noc/test/SelectorRTL_test.py
  scale_out/MeshMultiCgraRTL.py
  scale_out/RingMultiCgraRTL.py
  scale_out/test/MeshMultiCgraRTL_test.py
  scale_out/test/RingMultiCgraRTL_test.py
  systolic/CgraSystolicArrayRTL.py
  systolic/test/Cgra3x3MemRightAndBottomRTL_matmul_2x2_test.py
  tile/TileRTL.py
  tile/test/TileRTL_test.py
Labels: new feature

#81 [fix] Fix combinational loop in VectorAdderRTL.py
  fu/vector/VectorAdderRTL.py
Labels: bug

#82 Remove unused opt of tile[2] in weight stationary systolic array.
  doc/figures/weight_stationary_systolic_array.png
  systolic/test/Cgra3x3MemRightAndBottomRTL_matmul_2x2_test.py
Labels: documentation, cleanup

#83 Update CrossbarRTL.py
  noc/CrossbarRTL.py
Labels: bug

#85 Add dependencies information to README
  README.md
Labels: documentation
