Repository tancheng/VectorCGRA, pull requests merged in 2025-03, with the labels that each got.

#88 Add comment in workflow to remind users to update the submodules.
  .github/workflows/python-package.yml
  README.md
Labels: documentation

#89 Embed tile id for cgra modeling
  cgra/CgraRTL.py
  cgra/CgraTemplateRTL.py
Labels: cleanup

#90 Unify FUs between single-/multi-CGRA for rtl generation
  cgra/CgraRTL.py
  cgra/CgraTemplateRTL.py
  cgra/test/CgraRTL_test.py
  cgra/test/CgraTemplateRTL_test.py
  controller/ControllerRTL.py
  controller/test/ControllerRTL_test.py
  fu/vector/VectorAdderComboRTL.py
  fu/vector/VectorMulComboRTL.py
  lib/cmd_type.py
  noc/CrossbarRTL.py
  scale_out/MeshMultiCgraRTL.py
  scale_out/RingMultiCgraRTL.py
  scale_out/test/MeshMultiCgraRTL_test.py
  systolic/CgraSystolicArrayRTL.py
  tile/TileRTL.py
Labels: new feature, cleanup

#97 Avoid val depend on rdy in FpAddRTL.py
  fu/float/FpAddRTL.py
  fu/float/FpMulRTL.py
Labels: bug

#99 fix: added tag -Wno-CMPCONST to CgraTemplateRTL_test.py's verilator test
  cgra/test/CgraTemplateRTL_test.py
Labels: bug, cleanup

#100 X-prop and inferred latch fix proposal.
  mem/const/ConstQueueDynamicRTL.py
Labels: bug

#102 init_mem_done/addr reset insertion.
  mem/data/DataMemWithCrossbarRTL.py
Labels: bug

#107 [feature] Optional execute/route based on prologue count that is pre-…
  cgra/CgraRTL.py
  cgra/CgraTemplateRTL.py
  controller/ControllerRTL.py
  fu/flexible/FlexibleFuRTL.py
  fu/flexible/test/FlexibleFuRTL_hypothesis_test.py
  fu/flexible/test/FlexibleFuRTL_test.py
  lib/cmd_type.py
  lib/messages.py
  lib/util/common.py
  mem/ctrl/CtrlMemDynamicRTL.py
  noc/CrossbarRTL.py
  noc/test/CrossbarRTL_test.py
  systolic/CgraSystolicArrayRTL.py
  systolic/test/Cgra3x3MemRightAndBottomRTL_matmul_2x2_test.py
  tile/TileRTL.py
  tile/test/TileRTL_test.py
Labels: bug, new feature
